services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
